### ISSUE TITLE
Ability To Search Other Editions Of SNOMED-CT

### ISSUE THREAD

**Issue by bazini627** [anoopshah/Rdiagnosislist#9]
Just want to start off by saying thank you for the work that has gone into this. I stumbled across your package today thought it looked fantastic. Is there an ability to switch between different editions of SNOMED-CT? In my case I would be looking to search through the US edition but can see others also wanting to use this tool to search through various editions. Thank you again for the work on what is a great tool for those who have to work with SNOMED.

**Comment by anoopshah** [comment]
Dear Matt,

Thank you for your kind comments.
You can create different SNOMED CT dictionary environments using
loadSNOMED(), and choose any name e.g. MyVersionOfSNOMED. This is designed
for use with the NHS TRUD release format. You can then choose a specific
one to use in a function by sending the argument SNOMED when calling a
relevant function (e.g. SNOMEDconcept('Heart failure', SNOMED =
MyVersionOfSNOMED).
If you leave out the SNOMED argument, the function will search for an
object named 'SNOMED' in the global environment. Hence for interactive use
it is easiest to name the SNOMED environment you want to use 'SNOMED'.

If there is a particular SNOMED release format that it would be helpful to
use, please let me know, and I can look at incorporating it.
Thank you,

Anoop
